services:
  # 1. Spring Boot приложение (Docker)
  - type: web
    name: spring-server
    env: docker
    plan: free
    branch: feature/develop
    envVars:
      - key: JWT_SECRET
        value: MySuperSecretKey123!
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: my-postgres-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: my-postgres-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: my-postgres-db
          property: password

  # 2. База данных PostgreSQL
  - type: pserv
    name: my-postgres-db
    plan: free
