version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: sprint-db
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: extybr123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  app:
    build: .
    container_name: Sprint-server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: extybr123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always

volumes:
  pgdata: